# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: BuildAndTest

on: [push, pull_request]

jobs:
  industrial_ci:
    env:
      DOCKER_IMAGE: 'moveit/moveit:melodic-source'
      UPSTREAM_WORKSPACE: 'upstream.rosinstall'
      UNDERLAY: /root/ws_moveit
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
